{
    "url": "https://api.github.com/repos/pallets/flask/issues/1246",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1246/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1246/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1246/events",
    "html_url": "https://github.com/pallets/flask/issues/1246",
    "id": 48489103,
    "node_id": "MDU6SXNzdWU0ODQ4OTEwMw==",
    "number": 1246,
    "title": "Flask fails to start with use_reloader=True when using absolute import",
    "user": {
        "login": "mavroprovato",
        "id": 591686,
        "node_id": "MDQ6VXNlcjU5MTY4Ng==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/591686?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mavroprovato",
        "html_url": "https://github.com/mavroprovato",
        "followers_url": "https://api.github.com/users/mavroprovato/followers",
        "following_url": "https://api.github.com/users/mavroprovato/following{/other_user}",
        "gists_url": "https://api.github.com/users/mavroprovato/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mavroprovato/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mavroprovato/subscriptions",
        "organizations_url": "https://api.github.com/users/mavroprovato/orgs",
        "repos_url": "https://api.github.com/users/mavroprovato/repos",
        "events_url": "https://api.github.com/users/mavroprovato/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mavroprovato/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 14,
    "created_at": "2014-11-12T09:22:17Z",
    "updated_at": "2017-05-28T04:14:25Z",
    "closed_at": "2017-05-28T04:14:06Z",
    "author_association": "NONE",
    "body": "I'm using Flask v0.10.1 and I have the following project structure:\n\n```\ntest\n\u251c\u2500\u2500 api\n\u2502   \u251c\u2500\u2500 hello.py\n\u2502   \u2514\u2500\u2500 __init__.py\n\u251c\u2500\u2500 config\n\u2502   \u251c\u2500\u2500 config.py\n\u2502   \u2514\u2500\u2500 __init__.py\n\u2514\u2500\u2500 __init__.py\n```\n\nThe hello.py file is:\n\n``` python\nimport sys\nimport flask\nfrom test.config import config\n\napp = flask.Flask(__name__)\n\n@app.route('/hello')\ndef hello():\n    return config.MESSAGE\n\ndef main(argv):\n    reloader = '--reloader' in argv\n    print('Starting with reloader={}'.format(reloader))\n    app.run(host='0.0.0.0', port=8080, debug=True, use_reloader=reloader)\n\nif __name__ == '__main__':\n    main(sys.argv)\n```\n\nand the config.py is simply\n\n``` python\nMESSAGE = 'Hello!'\n```\n\nWhen I run `api.py` with `use_reloader=False` (`python -m test.api.hello`) the server starts correctly. If I run it with `use_reloader=True` (`python -m test.api.hello --reloader`) it fails with:\n\n```\nStarting with reloader=True\n * Running on http://0.0.0.0:8080/\n * Restarting with reloader\nTraceback (most recent call last):\n  File \"/home/kostas/Tmp/testproj/test/api/hello.py\", line 3, in <module>\n    from test.config import config\nImportError: No module named config\n```\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/62719180",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-62719180",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 62719180,
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyNzE5MTgw",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-11-12T13:45:28Z",
            "updated_at": "2014-11-12T13:45:28Z",
            "author_association": "MEMBER",
            "body": "Please check for stray `test.pyc` files. I used to be able to reproduce this before deleting the offending file in my pythonpath.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/62754729",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-62754729",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 62754729,
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyNzU0NzI5",
            "user": {
                "login": "mavroprovato",
                "id": 591686,
                "node_id": "MDQ6VXNlcjU5MTY4Ng==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/591686?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mavroprovato",
                "html_url": "https://github.com/mavroprovato",
                "followers_url": "https://api.github.com/users/mavroprovato/followers",
                "following_url": "https://api.github.com/users/mavroprovato/following{/other_user}",
                "gists_url": "https://api.github.com/users/mavroprovato/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mavroprovato/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mavroprovato/subscriptions",
                "organizations_url": "https://api.github.com/users/mavroprovato/orgs",
                "repos_url": "https://api.github.com/users/mavroprovato/repos",
                "events_url": "https://api.github.com/users/mavroprovato/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mavroprovato/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-11-12T17:14:09Z",
            "updated_at": "2014-11-12T17:14:09Z",
            "author_association": "NONE",
            "body": "Unfortunatelly, running `find . -name \"*.pyc\" -exec rm -rf {} \\;` before `python -m test.api.hello --reloader` does not make a difference\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/62818514",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-62818514",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 62818514,
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyODE4NTE0",
            "user": {
                "login": "pgk",
                "id": 500744,
                "node_id": "MDQ6VXNlcjUwMDc0NA==",
                "avatar_url": "https://avatars3.githubusercontent.com/u/500744?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/pgk",
                "html_url": "https://github.com/pgk",
                "followers_url": "https://api.github.com/users/pgk/followers",
                "following_url": "https://api.github.com/users/pgk/following{/other_user}",
                "gists_url": "https://api.github.com/users/pgk/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/pgk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/pgk/subscriptions",
                "organizations_url": "https://api.github.com/users/pgk/orgs",
                "repos_url": "https://api.github.com/users/pgk/repos",
                "events_url": "https://api.github.com/users/pgk/events{/privacy}",
                "received_events_url": "https://api.github.com/users/pgk/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-11-13T00:02:21Z",
            "updated_at": "2014-11-13T00:20:13Z",
            "author_association": "NONE",
            "body": "Is `test` visible in your [`PYTHONPATH`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH)?\n\n```\nPYTHONPATH=`pwd` python -m test.api.hello --reloader\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/62879141",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-62879141",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 62879141,
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyODc5MTQx",
            "user": {
                "login": "mavroprovato",
                "id": 591686,
                "node_id": "MDQ6VXNlcjU5MTY4Ng==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/591686?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mavroprovato",
                "html_url": "https://github.com/mavroprovato",
                "followers_url": "https://api.github.com/users/mavroprovato/followers",
                "following_url": "https://api.github.com/users/mavroprovato/following{/other_user}",
                "gists_url": "https://api.github.com/users/mavroprovato/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mavroprovato/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mavroprovato/subscriptions",
                "organizations_url": "https://api.github.com/users/mavroprovato/orgs",
                "repos_url": "https://api.github.com/users/mavroprovato/repos",
                "events_url": "https://api.github.com/users/mavroprovato/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mavroprovato/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-11-13T11:47:10Z",
            "updated_at": "2014-11-13T11:47:10Z",
            "author_association": "NONE",
            "body": "@pgk: With your command it works.\n\nI searched my environment for `test.pyc` files and I found the following (I'm using a virtualenv):\n\n```\n/home/kostas/Tmp/testenv/lib/python2.7/site-packages/setuptools/command/test.pyc\n/home/kostas/Tmp/testenv/lib/python2.7/site-packages/werkzeug/testsuite/test.pyc\n/home/kostas/Tmp/testenv/lib/python2.7/site-packages/werkzeug/test.pyc\n/usr/local/lib/python2.7/dist-packages/py-1.4.23-py2.7.egg/py/test.pyc\n/usr/lib/python2.7/dist-packages/setuptools/command/test.pyc\n/usr/lib/python2.7/dist-packages/reportlab/graphics/barcode/test.pyc\n/usr/lib/python2.7/dist-packages/chardet/test.pyc\n```\n\nIs there something wrong with my configuration? Or there is a conflict between some libraries?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/62887493",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-62887493",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 62887493,
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyODg3NDkz",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-11-13T13:07:48Z",
            "updated_at": "2014-11-13T13:07:48Z",
            "author_association": "MEMBER",
            "body": "Could you print sys.path in hello.py without the suggested command?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/62896758",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-62896758",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 62896758,
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyODk2NzU4",
            "user": {
                "login": "mavroprovato",
                "id": 591686,
                "node_id": "MDQ6VXNlcjU5MTY4Ng==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/591686?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mavroprovato",
                "html_url": "https://github.com/mavroprovato",
                "followers_url": "https://api.github.com/users/mavroprovato/followers",
                "following_url": "https://api.github.com/users/mavroprovato/following{/other_user}",
                "gists_url": "https://api.github.com/users/mavroprovato/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mavroprovato/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mavroprovato/subscriptions",
                "organizations_url": "https://api.github.com/users/mavroprovato/orgs",
                "repos_url": "https://api.github.com/users/mavroprovato/repos",
                "events_url": "https://api.github.com/users/mavroprovato/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mavroprovato/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-11-13T14:24:05Z",
            "updated_at": "2014-11-13T14:31:41Z",
            "author_association": "NONE",
            "body": "Here you are:\n\n```\n$ python -m test.api.hello\nStarting with reloader=False\nSys path: [\n    '',\n    '/home/kostas/Tmp/testenv/lib/python2.7',\n    '/home/kostas/Tmp/testenv/lib/python2.7/plat-x86_64-linux-gnu',\n    '/home/kostas/Tmp/testenv/lib/python2.7/lib-tk',\n    '/home/kostas/Tmp/testenv/lib/python2.7/lib-old',\n    '/home/kostas/Tmp/testenv/lib/python2.7/lib-dynload',\n    '/usr/lib/python2.7',\n    '/usr/lib/python2.7/plat-x86_64-linux-gnu',\n    '/usr/lib/python2.7/lib-tk',\n    '/home/kostas/Tmp/testenv/local/lib/python2.7/site-packages',\n    '/home/kostas/Tmp/testenv/lib/python2.7/site-packages'\n]\n * Running on http://0.0.0.0:8080/\n```\n\n_Edit_: When running it with the suggested command, the first (empty) entry is replaced by the actual working directory.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/62942176",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-62942176",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 62942176,
            "node_id": "MDEyOklzc3VlQ29tbWVudDYyOTQyMTc2",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-11-13T18:33:42Z",
            "updated_at": "2014-11-13T18:33:42Z",
            "author_association": "MEMBER",
            "body": " I suppose that when running with `--reloader`, you hit https://github.com/mitsuhiko/werkzeug/issues/461 (i.e. the current working directory disappears from the path, and the script's directory is added)\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/66278543",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-66278543",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 66278543,
            "node_id": "MDEyOklzc3VlQ29tbWVudDY2Mjc4NTQz",
            "user": {
                "login": "lynncyrin",
                "id": 5768468,
                "node_id": "MDQ6VXNlcjU3Njg0Njg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5768468?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/lynncyrin",
                "html_url": "https://github.com/lynncyrin",
                "followers_url": "https://api.github.com/users/lynncyrin/followers",
                "following_url": "https://api.github.com/users/lynncyrin/following{/other_user}",
                "gists_url": "https://api.github.com/users/lynncyrin/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/lynncyrin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/lynncyrin/subscriptions",
                "organizations_url": "https://api.github.com/users/lynncyrin/orgs",
                "repos_url": "https://api.github.com/users/lynncyrin/repos",
                "events_url": "https://api.github.com/users/lynncyrin/events{/privacy}",
                "received_events_url": "https://api.github.com/users/lynncyrin/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2014-12-09T12:57:29Z",
            "updated_at": "2014-12-09T12:57:29Z",
            "author_association": "NONE",
            "body": "Just wanted to note that I'm having the exact same issue, I switched my project structure around so I wouldn't have to add to PYTHONPATH, but it looks like I'm going to have to if I want to use reloader ?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/113097027",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-113097027",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 113097027,
            "node_id": "MDEyOklzc3VlQ29tbWVudDExMzA5NzAyNw==",
            "user": {
                "login": "eddwardo",
                "id": 1431465,
                "node_id": "MDQ6VXNlcjE0MzE0NjU=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/1431465?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/eddwardo",
                "html_url": "https://github.com/eddwardo",
                "followers_url": "https://api.github.com/users/eddwardo/followers",
                "following_url": "https://api.github.com/users/eddwardo/following{/other_user}",
                "gists_url": "https://api.github.com/users/eddwardo/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/eddwardo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/eddwardo/subscriptions",
                "organizations_url": "https://api.github.com/users/eddwardo/orgs",
                "repos_url": "https://api.github.com/users/eddwardo/repos",
                "events_url": "https://api.github.com/users/eddwardo/events{/privacy}",
                "received_events_url": "https://api.github.com/users/eddwardo/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-06-18T09:59:29Z",
            "updated_at": "2015-06-18T09:59:29Z",
            "author_association": "NONE",
            "body": "Same issue here, app fails to load absolute import when using debug=True. Debug=False works fine.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/113113409",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-113113409",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 113113409,
            "node_id": "MDEyOklzc3VlQ29tbWVudDExMzExMzQwOQ==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-06-18T11:14:30Z",
            "updated_at": "2015-06-18T11:14:30Z",
            "author_association": "MEMBER",
            "body": "The current solution is to avoid running your app via `python -m ...`.\n\nThe issue I linked above contains all the details and why this is an unfixable problem AFAIK\n\nOn 18 June 2015 11:59:41 CEST, \"Piotrek Szyma\u0144ski\" notifications@github.com wrote:\n\n> Same issue here, app fails to load absolute import when using\n> debug=True. Debug=False works fine.\n> \n> ---\n> \n> Reply to this email directly or view it on GitHub:\n> https://github.com/mitsuhiko/flask/issues/1246#issuecomment-113097027\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/113498463",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-113498463",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 113498463,
            "node_id": "MDEyOklzc3VlQ29tbWVudDExMzQ5ODQ2Mw==",
            "user": {
                "login": "mavroprovato",
                "id": 591686,
                "node_id": "MDQ6VXNlcjU5MTY4Ng==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/591686?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mavroprovato",
                "html_url": "https://github.com/mavroprovato",
                "followers_url": "https://api.github.com/users/mavroprovato/followers",
                "following_url": "https://api.github.com/users/mavroprovato/following{/other_user}",
                "gists_url": "https://api.github.com/users/mavroprovato/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mavroprovato/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mavroprovato/subscriptions",
                "organizations_url": "https://api.github.com/users/mavroprovato/orgs",
                "repos_url": "https://api.github.com/users/mavroprovato/repos",
                "events_url": "https://api.github.com/users/mavroprovato/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mavroprovato/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-06-19T12:25:40Z",
            "updated_at": "2015-06-19T12:25:40Z",
            "author_association": "NONE",
            "body": "@untitaker better solution is to run the app with\n\n```\nPYTHONPATH=`pwd` python -m test.api.hello --reloader\n```\n\njust as @pgk suggested. Actually, this is the only way that works for me.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/113501417",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-113501417",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 113501417,
            "node_id": "MDEyOklzc3VlQ29tbWVudDExMzUwMTQxNw==",
            "user": {
                "login": "eddwardo",
                "id": 1431465,
                "node_id": "MDQ6VXNlcjE0MzE0NjU=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/1431465?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/eddwardo",
                "html_url": "https://github.com/eddwardo",
                "followers_url": "https://api.github.com/users/eddwardo/followers",
                "following_url": "https://api.github.com/users/eddwardo/following{/other_user}",
                "gists_url": "https://api.github.com/users/eddwardo/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/eddwardo/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/eddwardo/subscriptions",
                "organizations_url": "https://api.github.com/users/eddwardo/orgs",
                "repos_url": "https://api.github.com/users/eddwardo/repos",
                "events_url": "https://api.github.com/users/eddwardo/events{/privacy}",
                "received_events_url": "https://api.github.com/users/eddwardo/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-06-19T12:35:12Z",
            "updated_at": "2015-06-19T12:35:12Z",
            "author_association": "NONE",
            "body": "That actually works, Thanks!\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/115690934",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-115690934",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 115690934,
            "node_id": "MDEyOklzc3VlQ29tbWVudDExNTY5MDkzNA==",
            "user": {
                "login": "bootc",
                "id": 796037,
                "node_id": "MDQ6VXNlcjc5NjAzNw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/796037?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/bootc",
                "html_url": "https://github.com/bootc",
                "followers_url": "https://api.github.com/users/bootc/followers",
                "following_url": "https://api.github.com/users/bootc/following{/other_user}",
                "gists_url": "https://api.github.com/users/bootc/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/bootc/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/bootc/subscriptions",
                "organizations_url": "https://api.github.com/users/bootc/orgs",
                "repos_url": "https://api.github.com/users/bootc/repos",
                "events_url": "https://api.github.com/users/bootc/events{/privacy}",
                "received_events_url": "https://api.github.com/users/bootc/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-06-26T13:36:29Z",
            "updated_at": "2015-06-26T13:36:29Z",
            "author_association": "NONE",
            "body": "I personally fixed this using the following in my equivalent of `hello.py`:\n\n``` python\n# Workaround for the werkzeug reloader removing the current directory from the\n# path. It's nasty, but it works! Inspired by:\n# https://github.com/mitsuhiko/flask/issues/1246\nos.environ['PYTHONPATH'] = os.getcwd()\n```\n\nJust do that before you call `app.run()` with the reloader enabled; that seems to fix it for me.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/304491661",
            "html_url": "https://github.com/pallets/flask/issues/1246#issuecomment-304491661",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1246",
            "id": 304491661,
            "node_id": "MDEyOklzc3VlQ29tbWVudDMwNDQ5MTY2MQ==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-05-28T04:14:06Z",
            "updated_at": "2017-05-28T04:14:25Z",
            "author_association": "MEMBER",
            "body": "We now encourage you to install your project in editable mode during development. `pip install -e .` This, and using the `flask` command, should fix any import issues."
        }
    ]
}