{
    "url": "https://api.github.com/repos/pallets/flask/issues/147",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/147/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/147/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/147/events",
    "html_url": "https://github.com/pallets/flask/issues/147",
    "id": 441179,
    "node_id": "MDU6SXNzdWU0NDExNzk=",
    "number": 147,
    "title": "pypy 1.4 and Flask Sessions",
    "user": {
        "login": "sebest",
        "id": 115339,
        "node_id": "MDQ6VXNlcjExNTMzOQ==",
        "avatar_url": "https://avatars0.githubusercontent.com/u/115339?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sebest",
        "html_url": "https://github.com/sebest",
        "followers_url": "https://api.github.com/users/sebest/followers",
        "following_url": "https://api.github.com/users/sebest/following{/other_user}",
        "gists_url": "https://api.github.com/users/sebest/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sebest/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sebest/subscriptions",
        "organizations_url": "https://api.github.com/users/sebest/orgs",
        "repos_url": "https://api.github.com/users/sebest/repos",
        "events_url": "https://api.github.com/users/sebest/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sebest/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 3,
    "created_at": "2010-11-26T23:48:37Z",
    "updated_at": "2013-07-26T22:25:22Z",
    "closed_at": "2013-07-26T22:25:22Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hello,\n\njust tried pypy 1.4 and go a strange bug when using Flask's sessions:\nhere is the traceback:\nhttp://paste.pocoo.org/show/296447/\n\na simple app that trigger the bug:\nhttp://paste.pocoo.org/show/296464/\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/569788",
            "html_url": "https://github.com/pallets/flask/issues/147#issuecomment-569788",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/147",
            "id": 569788,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU2OTc4OA==",
            "user": {
                "login": "sebest",
                "id": 115339,
                "node_id": "MDQ6VXNlcjExNTMzOQ==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/115339?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/sebest",
                "html_url": "https://github.com/sebest",
                "followers_url": "https://api.github.com/users/sebest/followers",
                "following_url": "https://api.github.com/users/sebest/following{/other_user}",
                "gists_url": "https://api.github.com/users/sebest/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/sebest/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/sebest/subscriptions",
                "organizations_url": "https://api.github.com/users/sebest/orgs",
                "repos_url": "https://api.github.com/users/sebest/repos",
                "events_url": "https://api.github.com/users/sebest/events{/privacy}",
                "received_events_url": "https://api.github.com/users/sebest/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2010-11-27T15:05:02Z",
            "updated_at": "2010-11-27T15:05:02Z",
            "author_association": "CONTRIBUTOR",
            "body": "it is quite easy to reproduce this using virtualenv -p PATH_TO_PYPY_1.4 thebug\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/19688561",
            "html_url": "https://github.com/pallets/flask/issues/147#issuecomment-19688561",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/147",
            "id": 19688561,
            "node_id": "MDEyOklzc3VlQ29tbWVudDE5Njg4NTYx",
            "user": {
                "login": "DasIch",
                "id": 182316,
                "node_id": "MDQ6VXNlcjE4MjMxNg==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/182316?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/DasIch",
                "html_url": "https://github.com/DasIch",
                "followers_url": "https://api.github.com/users/DasIch/followers",
                "following_url": "https://api.github.com/users/DasIch/following{/other_user}",
                "gists_url": "https://api.github.com/users/DasIch/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/DasIch/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/DasIch/subscriptions",
                "organizations_url": "https://api.github.com/users/DasIch/orgs",
                "repos_url": "https://api.github.com/users/DasIch/repos",
                "events_url": "https://api.github.com/users/DasIch/events{/privacy}",
                "received_events_url": "https://api.github.com/users/DasIch/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-06-19T14:46:10Z",
            "updated_at": "2013-06-19T14:46:10Z",
            "author_association": "CONTRIBUTOR",
            "body": "Is this still an issue?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/21651236",
            "html_url": "https://github.com/pallets/flask/issues/147#issuecomment-21651236",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/147",
            "id": 21651236,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIxNjUxMjM2",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2013-07-26T22:09:33Z",
            "updated_at": "2013-07-26T22:09:33Z",
            "author_association": "MEMBER",
            "body": "Please somebody close this, the issue is completely useless with an unavailable pastebin and both Flask and PyPy have come a long way.\n"
        }
    ]
}