{
    "url": "https://api.github.com/repos/pallets/flask/issues/1554",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1554/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1554/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1554/events",
    "html_url": "https://github.com/pallets/flask/issues/1554",
    "id": 100255434,
    "node_id": "MDU6SXNzdWUxMDAyNTU0MzQ=",
    "number": 1554,
    "title": "Help needed: 404 error on every page dynamic page of the application ",
    "user": {
        "login": "Alexis-benoist",
        "id": 4437159,
        "node_id": "MDQ6VXNlcjQ0MzcxNTk=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/4437159?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Alexis-benoist",
        "html_url": "https://github.com/Alexis-benoist",
        "followers_url": "https://api.github.com/users/Alexis-benoist/followers",
        "following_url": "https://api.github.com/users/Alexis-benoist/following{/other_user}",
        "gists_url": "https://api.github.com/users/Alexis-benoist/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Alexis-benoist/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Alexis-benoist/subscriptions",
        "organizations_url": "https://api.github.com/users/Alexis-benoist/orgs",
        "repos_url": "https://api.github.com/users/Alexis-benoist/repos",
        "events_url": "https://api.github.com/users/Alexis-benoist/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Alexis-benoist/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2015-08-11T08:18:15Z",
    "updated_at": "2015-08-11T15:00:02Z",
    "closed_at": "2015-08-11T15:00:02Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hello,\n\nI'm running into the problem described in stackoverflow [here](http://stackoverflow.com/questions/24437248/unexplainable-flask-404-errors).\n\nThe code is running on the server normally and on my colleagues computers. Though on my computer for every route is returning a 404 error, though static content is working. The capture below shows that I'm working on the good port and the route exists.\n\n<img width=\"1268\" alt=\"capture d ecran 2015-08-11 a 10 13 26\" src=\"https://cloud.githubusercontent.com/assets/4437159/9193157/abb09062-4011-11e5-98ef-7f8c7c17530a.png\">\n\nI reinstalled the virtuelenv and I still have this issues. Do you guys have ever encountered this problem?\nI'm using Python 2.7.6 and flask:\nFlask==0.10.1\nWerkzeug==0.10.4\nJinja2==2.7.3\nAny answer is welcome.\n\nCheers,\nAlexis.\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/129850015",
            "html_url": "https://github.com/pallets/flask/issues/1554#issuecomment-129850015",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1554",
            "id": 129850015,
            "node_id": "MDEyOklzc3VlQ29tbWVudDEyOTg1MDAxNQ==",
            "user": {
                "login": "Alexis-benoist",
                "id": 4437159,
                "node_id": "MDQ6VXNlcjQ0MzcxNTk=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/4437159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Alexis-benoist",
                "html_url": "https://github.com/Alexis-benoist",
                "followers_url": "https://api.github.com/users/Alexis-benoist/followers",
                "following_url": "https://api.github.com/users/Alexis-benoist/following{/other_user}",
                "gists_url": "https://api.github.com/users/Alexis-benoist/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Alexis-benoist/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Alexis-benoist/subscriptions",
                "organizations_url": "https://api.github.com/users/Alexis-benoist/orgs",
                "repos_url": "https://api.github.com/users/Alexis-benoist/repos",
                "events_url": "https://api.github.com/users/Alexis-benoist/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Alexis-benoist/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-08-11T11:59:53Z",
            "updated_at": "2015-08-11T12:00:13Z",
            "author_association": "CONTRIBUTOR",
            "body": "I have a better feel of why I get the error, in werkzeug/routing.py line 1432, the variable `self.subdomain` is `u'<invalid>'` so the path to match is `u'<invalid>|/admin/'` which is not matched.\n\nThough, if I try to match the string `'|/admin/'`, it is matched.\n\nDoes anyone knows why the subdomain could be `<invalid>` on my machine?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/129855507",
            "html_url": "https://github.com/pallets/flask/issues/1554#issuecomment-129855507",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1554",
            "id": 129855507,
            "node_id": "MDEyOklzc3VlQ29tbWVudDEyOTg1NTUwNw==",
            "user": {
                "login": "Alexis-benoist",
                "id": 4437159,
                "node_id": "MDQ6VXNlcjQ0MzcxNTk=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/4437159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Alexis-benoist",
                "html_url": "https://github.com/Alexis-benoist",
                "followers_url": "https://api.github.com/users/Alexis-benoist/followers",
                "following_url": "https://api.github.com/users/Alexis-benoist/following{/other_user}",
                "gists_url": "https://api.github.com/users/Alexis-benoist/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Alexis-benoist/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Alexis-benoist/subscriptions",
                "organizations_url": "https://api.github.com/users/Alexis-benoist/orgs",
                "repos_url": "https://api.github.com/users/Alexis-benoist/repos",
                "events_url": "https://api.github.com/users/Alexis-benoist/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Alexis-benoist/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-08-11T12:23:06Z",
            "updated_at": "2015-08-11T12:27:54Z",
            "author_association": "CONTRIBUTOR",
            "body": "I dig a bit deeper and I saw something in bind_to_environ line 1227 (werkzeug/routing), the `real_server_name` is `[u'test']`and the `cur_server_name` is `['localhost:5000']` so the domain name is `'invalid'`.\n\n```\n# This can happen even with valid configs if the server was\n# accesssed directly by IP address under some situations.\n# Instead of raising an exception like in Werkzeug 0.7 or\n# earlier we go by an invalid subdomain which will result\n# in a 404 error on matching.\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/129857944",
            "html_url": "https://github.com/pallets/flask/issues/1554#issuecomment-129857944",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1554",
            "id": 129857944,
            "node_id": "MDEyOklzc3VlQ29tbWVudDEyOTg1Nzk0NA==",
            "user": {
                "login": "Alexis-benoist",
                "id": 4437159,
                "node_id": "MDQ6VXNlcjQ0MzcxNTk=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/4437159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Alexis-benoist",
                "html_url": "https://github.com/Alexis-benoist",
                "followers_url": "https://api.github.com/users/Alexis-benoist/followers",
                "following_url": "https://api.github.com/users/Alexis-benoist/following{/other_user}",
                "gists_url": "https://api.github.com/users/Alexis-benoist/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Alexis-benoist/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Alexis-benoist/subscriptions",
                "organizations_url": "https://api.github.com/users/Alexis-benoist/orgs",
                "repos_url": "https://api.github.com/users/Alexis-benoist/repos",
                "events_url": "https://api.github.com/users/Alexis-benoist/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Alexis-benoist/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-08-11T12:34:42Z",
            "updated_at": "2015-08-11T12:34:42Z",
            "author_association": "CONTRIBUTOR",
            "body": "I solved my problem, I just changed `SERVER_NAME` in the config. Maybe it could be pertinent to issue a warning if the serveur_name doesn't match the real_server_name. I can create an issue in werkzeug, if you find it pertinent.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/129919321",
            "html_url": "https://github.com/pallets/flask/issues/1554#issuecomment-129919321",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1554",
            "id": 129919321,
            "node_id": "MDEyOklzc3VlQ29tbWVudDEyOTkxOTMyMQ==",
            "user": {
                "login": "Alexis-benoist",
                "id": 4437159,
                "node_id": "MDQ6VXNlcjQ0MzcxNTk=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/4437159?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Alexis-benoist",
                "html_url": "https://github.com/Alexis-benoist",
                "followers_url": "https://api.github.com/users/Alexis-benoist/followers",
                "following_url": "https://api.github.com/users/Alexis-benoist/following{/other_user}",
                "gists_url": "https://api.github.com/users/Alexis-benoist/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Alexis-benoist/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Alexis-benoist/subscriptions",
                "organizations_url": "https://api.github.com/users/Alexis-benoist/orgs",
                "repos_url": "https://api.github.com/users/Alexis-benoist/repos",
                "events_url": "https://api.github.com/users/Alexis-benoist/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Alexis-benoist/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2015-08-11T15:00:01Z",
            "updated_at": "2015-08-11T15:00:01Z",
            "author_association": "CONTRIBUTOR",
            "body": "If posted the issue on Werkzeug repo: https://github.com/mitsuhiko/werkzeug/issues/760\n"
        }
    ]
}