{
    "url": "https://api.github.com/repos/pallets/flask/issues/1679",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1679/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1679/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1679/events",
    "html_url": "https://github.com/pallets/flask/pull/1679",
    "id": 124607794,
    "node_id": "MDExOlB1bGxSZXF1ZXN0NTQ5MTEyMDE=",
    "number": 1679,
    "title": "Werkzeug should not block propagated exceptions from Flask",
    "user": {
        "login": "miguelgrinberg",
        "id": 2715854,
        "node_id": "MDQ6VXNlcjI3MTU4NTQ=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/2715854?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/miguelgrinberg",
        "html_url": "https://github.com/miguelgrinberg",
        "followers_url": "https://api.github.com/users/miguelgrinberg/followers",
        "following_url": "https://api.github.com/users/miguelgrinberg/following{/other_user}",
        "gists_url": "https://api.github.com/users/miguelgrinberg/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/miguelgrinberg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/miguelgrinberg/subscriptions",
        "organizations_url": "https://api.github.com/users/miguelgrinberg/orgs",
        "repos_url": "https://api.github.com/users/miguelgrinberg/repos",
        "events_url": "https://api.github.com/users/miguelgrinberg/events{/privacy}",
        "received_events_url": "https://api.github.com/users/miguelgrinberg/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": {
        "login": "davidism",
        "id": 1242887,
        "node_id": "MDQ6VXNlcjEyNDI4ODc=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/davidism",
        "html_url": "https://github.com/davidism",
        "followers_url": "https://api.github.com/users/davidism/followers",
        "following_url": "https://api.github.com/users/davidism/following{/other_user}",
        "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
        "organizations_url": "https://api.github.com/users/davidism/orgs",
        "repos_url": "https://api.github.com/users/davidism/repos",
        "events_url": "https://api.github.com/users/davidism/events{/privacy}",
        "received_events_url": "https://api.github.com/users/davidism/received_events",
        "type": "User",
        "site_admin": false
    },
    "assignees": [
        {
            "login": "davidism",
            "id": 1242887,
            "node_id": "MDQ6VXNlcjEyNDI4ODc=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/davidism",
            "html_url": "https://github.com/davidism",
            "followers_url": "https://api.github.com/users/davidism/followers",
            "following_url": "https://api.github.com/users/davidism/following{/other_user}",
            "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
            "organizations_url": "https://api.github.com/users/davidism/orgs",
            "repos_url": "https://api.github.com/users/davidism/repos",
            "events_url": "https://api.github.com/users/davidism/events{/privacy}",
            "received_events_url": "https://api.github.com/users/davidism/received_events",
            "type": "User",
            "site_admin": false
        }
    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2016-01-02T19:34:01Z",
    "updated_at": "2018-10-23T17:43:41Z",
    "closed_at": "2016-01-26T06:17:04Z",
    "author_association": "MEMBER",
    "pull_request": {
        "url": "https://api.github.com/repos/pallets/flask/pulls/1679",
        "html_url": "https://github.com/pallets/flask/pull/1679",
        "diff_url": "https://github.com/pallets/flask/pull/1679.diff",
        "patch_url": "https://github.com/pallets/flask/pull/1679.patch"
    },
    "body": "Fixes #1674.\n\nBy having Werkzeug always configured to let exceptions through we achieve the correct behavior for Flask. If Flask is configured to propagate exceptions (implicitly or explicitly, doesn't matter), then Werkzeug will get these exceptions and pass them through as well. If Flask is configured to not propagate exceptions, then Werkzeug will never see them, so no harm done if it is configured to pass them.\n\nIt looks like there is no testing for the new cli, so I have only added a test for the `app.run()` way of starting a server.\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/174851729",
            "html_url": "https://github.com/pallets/flask/pull/1679#issuecomment-174851729",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1679",
            "id": 174851729,
            "node_id": "MDEyOklzc3VlQ29tbWVudDE3NDg1MTcyOQ==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-01-26T06:19:04Z",
            "updated_at": "2016-01-26T06:19:04Z",
            "author_association": "MEMBER",
            "body": "I don't know why I never noticed that PyCharm wasn't breaking on exceptions, but it works as expected and as described in the docs now.  Thanks for fixing this.\n"
        }
    ]
}