{
    "url": "https://api.github.com/repos/pallets/flask/issues/1941",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1941/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1941/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1941/events",
    "html_url": "https://github.com/pallets/flask/issues/1941",
    "id": 163428621,
    "node_id": "MDU6SXNzdWUxNjM0Mjg2MjE=",
    "number": 1941,
    "title": "Flask fails to reload upon Traceback",
    "user": {
        "login": "ivanlmj",
        "id": 7580855,
        "node_id": "MDQ6VXNlcjc1ODA4NTU=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/7580855?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ivanlmj",
        "html_url": "https://github.com/ivanlmj",
        "followers_url": "https://api.github.com/users/ivanlmj/followers",
        "following_url": "https://api.github.com/users/ivanlmj/following{/other_user}",
        "gists_url": "https://api.github.com/users/ivanlmj/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ivanlmj/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ivanlmj/subscriptions",
        "organizations_url": "https://api.github.com/users/ivanlmj/orgs",
        "repos_url": "https://api.github.com/users/ivanlmj/repos",
        "events_url": "https://api.github.com/users/ivanlmj/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ivanlmj/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": true,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 3,
    "created_at": "2016-07-01T16:16:58Z",
    "updated_at": "2018-05-01T18:10:31Z",
    "closed_at": "2016-07-05T15:38:24Z",
    "author_association": "NONE",
    "body": "I have the following Flask app running in a Stage server, and I realized that some requests were affecting its operation, causing Tracebacks and with this, the Flask app was still running as a process, but not answering any sort of request, neither giving a kind of Internal Server Error (5xx).\n\nHere is my code:\n\n``` python\n#!/usr/bin/python\n# -*- coding: utf-8 -*-\n\nfrom flask import Flask, jsonify\nfrom flask_limiter import Limiter\nfrom flask_limiter.util import get_remote_address\n\napp = Flask(__name__)\napp.config['JSON_AS_ASCII'] = False\n\nlimiter = Limiter (\n    app,\n    key_func=get_remote_address,\n    global_limits=[\"180 per day\",\"30 per hour\"]\n)\n\n@app.after_request\ndef server_response(response):\n    response.headers[\"Server\"] = \"WS\"\n    return response\n\n@app.route('/json')\ndef f_json():\n\n    d = { \"result\":[\n                {\"id\":\"1\",\"name\":\"John\",\"email\":\"john-flask@gmail.com\"},\n                {\"id\":\"2\",\"name\":\"NIkolas\",\"email\":\"nikolas-flask@gmail.com\"},\n        {\"id\":\"3\",\"name\":\"Samanta\",\"email\":\"samanta-flask@gmail.com\"}\n    ]}\n    return jsonify(d)\n\nif __name__ == '__main__':\n    app.run(host='0.0.0.0', port=80, debug=True)\n```\n\nHere is what I found in the debug, which caused the Traceback (and Flask was still running, but not answering any request).\n\n```\n191.96.249.231 - - [30/Jun/2016 19:11:47] \"GET /plugins/system/plugin_googlemap2/plugin_googlemap2_proxy.php?url=http://191.96.249.231/shodanhq HTTP/1.0\" 404 -\nException in thread Thread-2:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 810, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 763, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 659, in inner\n    srv.serve_forever()\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 499, in serve_forever\n    HTTPServer.serve_forever(self)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 238, in serve_forever\n    self._handle_request_noblock()\n  File \"/usr/lib/python2.7/SocketServer.py\", line 297, in _handle_request_noblock\n    self.handle_error(request, client_address)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 295, in _handle_request_noblock\n    self.process_request(request, client_address)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 321, in process_request\n    self.finish_request(request, client_address)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 334, in finish_request\n    self.RequestHandlerClass(request, client_address, self)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 649, in __init__\n    self.handle()\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 216, in handle\n    rv = BaseHTTPRequestHandler.handle(self)\n  File \"/usr/lib/python2.7/BaseHTTPServer.py\", line 340, in handle\n    self.handle_one_request()\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 251, in handle_one_request\n    return self.run_wsgi()\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 193, in run_wsgi\n    execute(self.server.app)\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 184, in execute\n    write(data)\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 149, in write\n    self.send_response(int(code), msg)\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 260, in send_response\n    self.wfile.write(hdr.encode('ascii'))\nIOError: [Errno 32] Broken pipe\n```\n\nIt also happened in this situation, but I believe that \"Connection Reset by Peer\" was already addressed and fixed, (https://github.com/miguelgrinberg/Flask-SocketIO/issues/184), but I believe it is worth to be mentioned regarding the data which was requested to Flask (it really caught my attention...)\n\n```\n169.229.3.91 - - [29/Jun/2016 09:12:37] \"0<B0>$e<AE>x<D4>^?<AB><AC>1<E8><CF>O\u06da<9C>^K@<BA><D2><FE><D4>q_^]i=AS%<D7>`I<CA>`<8F><C8>6<E5>E^SX)B<A5>-{^RoK^BT<E4><82>}O'\\<BB><8B><E4>a<86>\" 400 -\nException in thread Thread-2:\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/threading.py\", line 810, in __bootstrap_inner\n    self.run()\n  File \"/usr/lib/python2.7/threading.py\", line 763, in run\n    self.__target(*self.__args, **self.__kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 659, in inner\n    srv.serve_forever()\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 499, in serve_forever\n    HTTPServer.serve_forever(self)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 238, in serve_forever\n    self._handle_request_noblock()\n  File \"/usr/lib/python2.7/SocketServer.py\", line 297, in _handle_request_noblock\n    self.handle_error(request, client_address)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 295, in _handle_request_noblock\n    self.process_request(request, client_address)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 321, in process_request\n    self.finish_request(request, client_address)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 334, in finish_request\n    self.RequestHandlerClass(request, client_address, self)\n  File \"/usr/lib/python2.7/SocketServer.py\", line 649, in __init__\n    self.handle()\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 216, in handle\n    rv = BaseHTTPRequestHandler.handle(self)\n  File \"/usr/lib/python2.7/BaseHTTPServer.py\", line 340, in handle\n    self.handle_one_request()\n  File \"/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py\", line 247, in handle_one_request\n    self.raw_requestline = self.rfile.readline()\nIOError: [Errno 104] Connection reset by peer\n```\n\nI believe that it would be interesting to have a kind of \"recovery\" for Flask, or a better way to deal with it, without staying hanged..\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/230386846",
            "html_url": "https://github.com/pallets/flask/issues/1941#issuecomment-230386846",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1941",
            "id": 230386846,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzMDM4Njg0Ng==",
            "user": {
                "login": "gnanam336",
                "id": 8732789,
                "node_id": "MDQ6VXNlcjg3MzI3ODk=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/8732789?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/gnanam336",
                "html_url": "https://github.com/gnanam336",
                "followers_url": "https://api.github.com/users/gnanam336/followers",
                "following_url": "https://api.github.com/users/gnanam336/following{/other_user}",
                "gists_url": "https://api.github.com/users/gnanam336/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/gnanam336/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gnanam336/subscriptions",
                "organizations_url": "https://api.github.com/users/gnanam336/orgs",
                "repos_url": "https://api.github.com/users/gnanam336/repos",
                "events_url": "https://api.github.com/users/gnanam336/events{/privacy}",
                "received_events_url": "https://api.github.com/users/gnanam336/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-07-05T04:48:10Z",
            "updated_at": "2016-07-05T04:48:10Z",
            "author_association": "NONE",
            "body": "Encountering the same problem in Server Sent Events\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/230515527",
            "html_url": "https://github.com/pallets/flask/issues/1941#issuecomment-230515527",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1941",
            "id": 230515527,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzMDUxNTUyNw==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-07-05T15:38:22Z",
            "updated_at": "2016-07-05T15:38:22Z",
            "author_association": "MEMBER",
            "body": "duplicate of pallets/werkzeug#954\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/230537234",
            "html_url": "https://github.com/pallets/flask/issues/1941#issuecomment-230537234",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1941",
            "id": 230537234,
            "node_id": "MDEyOklzc3VlQ29tbWVudDIzMDUzNzIzNA==",
            "user": {
                "login": "ivanlmj",
                "id": 7580855,
                "node_id": "MDQ6VXNlcjc1ODA4NTU=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/7580855?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ivanlmj",
                "html_url": "https://github.com/ivanlmj",
                "followers_url": "https://api.github.com/users/ivanlmj/followers",
                "following_url": "https://api.github.com/users/ivanlmj/following{/other_user}",
                "gists_url": "https://api.github.com/users/ivanlmj/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ivanlmj/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ivanlmj/subscriptions",
                "organizations_url": "https://api.github.com/users/ivanlmj/orgs",
                "repos_url": "https://api.github.com/users/ivanlmj/repos",
                "events_url": "https://api.github.com/users/ivanlmj/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ivanlmj/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-07-05T16:56:57Z",
            "updated_at": "2016-07-05T16:56:57Z",
            "author_association": "NONE",
            "body": "Thank you @davidism \n"
        }
    ]
}