{
    "url": "https://api.github.com/repos/pallets/flask/issues/1995",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/1995/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/1995/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/1995/events",
    "html_url": "https://github.com/pallets/flask/issues/1995",
    "id": 173580786,
    "node_id": "MDU6SXNzdWUxNzM1ODA3ODY=",
    "number": 1995,
    "title": "No response and No exception traceback when render_template failed and DEBUG=True",
    "user": {
        "login": "guyskk",
        "id": 6367792,
        "node_id": "MDQ6VXNlcjYzNjc3OTI=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/6367792?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/guyskk",
        "html_url": "https://github.com/guyskk",
        "followers_url": "https://api.github.com/users/guyskk/followers",
        "following_url": "https://api.github.com/users/guyskk/following{/other_user}",
        "gists_url": "https://api.github.com/users/guyskk/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/guyskk/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/guyskk/subscriptions",
        "organizations_url": "https://api.github.com/users/guyskk/orgs",
        "repos_url": "https://api.github.com/users/guyskk/repos",
        "events_url": "https://api.github.com/users/guyskk/events{/privacy}",
        "received_events_url": "https://api.github.com/users/guyskk/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 130597497,
            "node_id": "MDU6TGFiZWwxMzA1OTc0OTc=",
            "url": "https://api.github.com/repos/pallets/flask/labels/blocker",
            "name": "blocker",
            "color": "b60205",
            "default": false,
            "description": null
        },
        {
            "id": 135583063,
            "node_id": "MDU6TGFiZWwxMzU1ODMwNjM=",
            "url": "https://api.github.com/repos/pallets/flask/labels/bug",
            "name": "bug",
            "color": "d93f0b",
            "default": true,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 22,
    "created_at": "2016-08-27T06:14:30Z",
    "updated_at": "2017-05-29T19:50:13Z",
    "closed_at": "2017-05-29T19:50:13Z",
    "author_association": "NONE",
    "body": "Here is the code:\n\napp.py\n\n```\nfrom flask import Flask, render_template\n\napp = Flask(__name__)\napp.config['DEBUG'] = True\n\n@app.route('/')\ndef index():\n    return render_template('unknown')\n\nif __name__ == '__main__':\n    from werkzeug.serving import run_simple\n    run_simple('127.0.0.1', 5000, app)\n```\n\nRun it by \n\n```\npython app.py\n```\n\nor  \n\n```\nexport FLASK_APP=app.py \nflask run\n```\n\nthen visit `http://127.0.0.1:5000` will see `ERR_EMPTY_RESPONSE` in browser and nothing in console.\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242899524",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242899524",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242899524,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjg5OTUyNA==",
            "user": {
                "login": "liuliqiang",
                "id": 9395418,
                "node_id": "MDQ6VXNlcjkzOTU0MTg=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/9395418?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/liuliqiang",
                "html_url": "https://github.com/liuliqiang",
                "followers_url": "https://api.github.com/users/liuliqiang/followers",
                "following_url": "https://api.github.com/users/liuliqiang/following{/other_user}",
                "gists_url": "https://api.github.com/users/liuliqiang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/liuliqiang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/liuliqiang/subscriptions",
                "organizations_url": "https://api.github.com/users/liuliqiang/orgs",
                "repos_url": "https://api.github.com/users/liuliqiang/repos",
                "events_url": "https://api.github.com/users/liuliqiang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/liuliqiang/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-27T06:23:43Z",
            "updated_at": "2016-08-27T06:31:53Z",
            "author_association": "NONE",
            "body": "you are using werkzueg's `simple_run`, in this way , `app.config.DEBUG` will not work, if you want it to work , you should use:\n`run_simple('127.0.0.1', 5000, app, use_debugger=True)` \nor \n`app.run('127.0.0.1', 5000, debug=True)`\n\nif you want to use `config.DEBUG = True` work, you may run as wsgi server.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242900697",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242900697",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242900697,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjkwMDY5Nw==",
            "user": {
                "login": "guyskk",
                "id": 6367792,
                "node_id": "MDQ6VXNlcjYzNjc3OTI=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/6367792?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/guyskk",
                "html_url": "https://github.com/guyskk",
                "followers_url": "https://api.github.com/users/guyskk/followers",
                "following_url": "https://api.github.com/users/guyskk/following{/other_user}",
                "gists_url": "https://api.github.com/users/guyskk/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/guyskk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/guyskk/subscriptions",
                "organizations_url": "https://api.github.com/users/guyskk/orgs",
                "repos_url": "https://api.github.com/users/guyskk/repos",
                "events_url": "https://api.github.com/users/guyskk/events{/privacy}",
                "received_events_url": "https://api.github.com/users/guyskk/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-27T06:55:51Z",
            "updated_at": "2016-08-27T06:55:51Z",
            "author_association": "NONE",
            "body": "I expect it print exception traceback in console and show 500 internal server error in browser.\nwhen DEBUG is False, it will print exception traceback and show 500 in browser, but when DEBUG is True, it not, so I think it is a bug.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242901063",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242901063",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242901063,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjkwMTA2Mw==",
            "user": {
                "login": "liuliqiang",
                "id": 9395418,
                "node_id": "MDQ6VXNlcjkzOTU0MTg=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/9395418?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/liuliqiang",
                "html_url": "https://github.com/liuliqiang",
                "followers_url": "https://api.github.com/users/liuliqiang/followers",
                "following_url": "https://api.github.com/users/liuliqiang/following{/other_user}",
                "gists_url": "https://api.github.com/users/liuliqiang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/liuliqiang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/liuliqiang/subscriptions",
                "organizations_url": "https://api.github.com/users/liuliqiang/orgs",
                "repos_url": "https://api.github.com/users/liuliqiang/repos",
                "events_url": "https://api.github.com/users/liuliqiang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/liuliqiang/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-27T07:04:23Z",
            "updated_at": "2016-08-27T07:04:23Z",
            "author_association": "NONE",
            "body": "@guyskk  which version Flask does you using?\ni checkout at v0.10.1 it print exception trackback in console when DEBUG is True and not print when DEBUG is False\nand at v0.11.1 both DEBUG is True or False, it show trackback in console.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242901137",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242901137",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242901137,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjkwMTEzNw==",
            "user": {
                "login": "guyskk",
                "id": 6367792,
                "node_id": "MDQ6VXNlcjYzNjc3OTI=",
                "avatar_url": "https://avatars2.githubusercontent.com/u/6367792?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/guyskk",
                "html_url": "https://github.com/guyskk",
                "followers_url": "https://api.github.com/users/guyskk/followers",
                "following_url": "https://api.github.com/users/guyskk/following{/other_user}",
                "gists_url": "https://api.github.com/users/guyskk/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/guyskk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/guyskk/subscriptions",
                "organizations_url": "https://api.github.com/users/guyskk/orgs",
                "repos_url": "https://api.github.com/users/guyskk/repos",
                "events_url": "https://api.github.com/users/guyskk/events{/privacy}",
                "received_events_url": "https://api.github.com/users/guyskk/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-27T07:05:47Z",
            "updated_at": "2016-08-27T07:05:47Z",
            "author_association": "NONE",
            "body": "@luke0922 flask 0.11.1 and python3.5\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242903854",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242903854",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242903854,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjkwMzg1NA==",
            "user": {
                "login": "liuliqiang",
                "id": 9395418,
                "node_id": "MDQ6VXNlcjkzOTU0MTg=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/9395418?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/liuliqiang",
                "html_url": "https://github.com/liuliqiang",
                "followers_url": "https://api.github.com/users/liuliqiang/followers",
                "following_url": "https://api.github.com/users/liuliqiang/following{/other_user}",
                "gists_url": "https://api.github.com/users/liuliqiang/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/liuliqiang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/liuliqiang/subscriptions",
                "organizations_url": "https://api.github.com/users/liuliqiang/orgs",
                "repos_url": "https://api.github.com/users/liuliqiang/repos",
                "events_url": "https://api.github.com/users/liuliqiang/events{/privacy}",
                "received_events_url": "https://api.github.com/users/liuliqiang/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-27T08:10:39Z",
            "updated_at": "2016-08-27T08:10:39Z",
            "author_association": "NONE",
            "body": "@guyskk  it seems work as you said, i just try in python 3.5.1 and get the same result, maybe it's a bug.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242912475",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242912475",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242912475,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjkxMjQ3NQ==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-27T11:42:55Z",
            "updated_at": "2016-08-27T11:42:55Z",
            "author_association": "MEMBER",
            "body": "Can reproduce. No problems with Python 2.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242923130",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242923130",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242923130,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjkyMzEzMA==",
            "user": {
                "login": "qingyunha",
                "id": 5804868,
                "node_id": "MDQ6VXNlcjU4MDQ4Njg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5804868?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/qingyunha",
                "html_url": "https://github.com/qingyunha",
                "followers_url": "https://api.github.com/users/qingyunha/followers",
                "following_url": "https://api.github.com/users/qingyunha/following{/other_user}",
                "gists_url": "https://api.github.com/users/qingyunha/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/qingyunha/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/qingyunha/subscriptions",
                "organizations_url": "https://api.github.com/users/qingyunha/orgs",
                "repos_url": "https://api.github.com/users/qingyunha/repos",
                "events_url": "https://api.github.com/users/qingyunha/events{/privacy}",
                "received_events_url": "https://api.github.com/users/qingyunha/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-27T15:20:01Z",
            "updated_at": "2016-08-27T15:20:01Z",
            "author_association": "NONE",
            "body": "I reproduced this with flask 0.11.1 and python 3.5.2\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242949491",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242949491",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242949491,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk0OTQ5MQ==",
            "user": {
                "login": "qingyunha",
                "id": 5804868,
                "node_id": "MDQ6VXNlcjU4MDQ4Njg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5804868?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/qingyunha",
                "html_url": "https://github.com/qingyunha",
                "followers_url": "https://api.github.com/users/qingyunha/followers",
                "following_url": "https://api.github.com/users/qingyunha/following{/other_user}",
                "gists_url": "https://api.github.com/users/qingyunha/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/qingyunha/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/qingyunha/subscriptions",
                "organizations_url": "https://api.github.com/users/qingyunha/orgs",
                "repos_url": "https://api.github.com/users/qingyunha/repos",
                "events_url": "https://api.github.com/users/qingyunha/events{/privacy}",
                "received_events_url": "https://api.github.com/users/qingyunha/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T00:58:48Z",
            "updated_at": "2016-08-28T00:58:48Z",
            "author_association": "NONE",
            "body": "I found the `jinja2.exceptions.TemplateNotFound` exception was catch by wrong place\n\n``` python\n        try:\n            execute(self.server.app)\n        except (socket.error, socket.timeout) as e: # go here\n            self.connection_dropped(e, environ)\n        except Exception:\n            if self.server.passthrough_errors:\n                raise\n```\n\nand  in python3.5\n\n``` python\nissubclass(jinja2.exceptions.TemplateNotFound, socket.error) \nTrue\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242951807",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242951807",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242951807,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk1MTgwNw==",
            "user": {
                "login": "qingyunha",
                "id": 5804868,
                "node_id": "MDQ6VXNlcjU4MDQ4Njg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5804868?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/qingyunha",
                "html_url": "https://github.com/qingyunha",
                "followers_url": "https://api.github.com/users/qingyunha/followers",
                "following_url": "https://api.github.com/users/qingyunha/following{/other_user}",
                "gists_url": "https://api.github.com/users/qingyunha/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/qingyunha/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/qingyunha/subscriptions",
                "organizations_url": "https://api.github.com/users/qingyunha/orgs",
                "repos_url": "https://api.github.com/users/qingyunha/repos",
                "events_url": "https://api.github.com/users/qingyunha/events{/privacy}",
                "received_events_url": "https://api.github.com/users/qingyunha/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T02:12:10Z",
            "updated_at": "2016-08-28T02:12:10Z",
            "author_association": "NONE",
            "body": "here is the thing:\n\n``` python\nIn [23]: jinja2.exceptions.TemplateNotFound.__bases__\nOut[23]: (OSError, LookupError, jinja2.exceptions.TemplateError)\n\nIn [24]: socket.error is OSError\nOut[24]: True\n\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242964183",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242964183",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242964183,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NDE4Mw==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T09:03:32Z",
            "updated_at": "2016-08-28T09:03:32Z",
            "author_association": "MEMBER",
            "body": "I see, I think under Python 3 we should use one of the other error types that the socket module has to offer: https://docs.python.org/3/library/socket.html#exceptions -- not sure if `herror` and `gaierror` catch everything though.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242964219",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242964219",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242964219,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NDIxOQ==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T09:04:28Z",
            "updated_at": "2016-08-28T09:04:28Z",
            "author_association": "MEMBER",
            "body": "Also thank you so much @qingyunha for finding this!\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242964303",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242964303",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242964303,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NDMwMw==",
            "user": {
                "login": "mitsuhiko",
                "id": 7396,
                "node_id": "MDQ6VXNlcjczOTY=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/7396?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mitsuhiko",
                "html_url": "https://github.com/mitsuhiko",
                "followers_url": "https://api.github.com/users/mitsuhiko/followers",
                "following_url": "https://api.github.com/users/mitsuhiko/following{/other_user}",
                "gists_url": "https://api.github.com/users/mitsuhiko/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mitsuhiko/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mitsuhiko/subscriptions",
                "organizations_url": "https://api.github.com/users/mitsuhiko/orgs",
                "repos_url": "https://api.github.com/users/mitsuhiko/repos",
                "events_url": "https://api.github.com/users/mitsuhiko/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mitsuhiko/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T09:06:08Z",
            "updated_at": "2016-08-28T09:06:08Z",
            "author_association": "MEMBER",
            "body": "Cool stuff. I think we could keep a tuple of error types for socket stuff in the compat module and catch on that.\n\nNot my favorite change. \n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242964348",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242964348",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242964348,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NDM0OA==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T09:07:08Z",
            "updated_at": "2016-08-28T09:07:08Z",
            "author_association": "MEMBER",
            "body": "Apparently this change was done in Python 3.3 too.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242964448",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242964448",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242964448,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NDQ0OA==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T09:09:42Z",
            "updated_at": "2016-08-28T09:09:42Z",
            "author_association": "MEMBER",
            "body": "BTW, the reason this exception even bubbles up this far is https://github.com/pallets/werkzeug/issues/954\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242964468",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242964468",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242964468,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NDQ2OA==",
            "user": {
                "login": "mitsuhiko",
                "id": 7396,
                "node_id": "MDQ6VXNlcjczOTY=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/7396?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mitsuhiko",
                "html_url": "https://github.com/mitsuhiko",
                "followers_url": "https://api.github.com/users/mitsuhiko/followers",
                "following_url": "https://api.github.com/users/mitsuhiko/following{/other_user}",
                "gists_url": "https://api.github.com/users/mitsuhiko/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mitsuhiko/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mitsuhiko/subscriptions",
                "organizations_url": "https://api.github.com/users/mitsuhiko/orgs",
                "repos_url": "https://api.github.com/users/mitsuhiko/repos",
                "events_url": "https://api.github.com/users/mitsuhiko/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mitsuhiko/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T09:10:12Z",
            "updated_at": "2016-08-28T09:10:12Z",
            "author_association": "MEMBER",
            "body": "We could try to detect the actual error codes relevant for socket loss. \n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242966274",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242966274",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242966274,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NjI3NA==",
            "user": {
                "login": "qingyunha",
                "id": 5804868,
                "node_id": "MDQ6VXNlcjU4MDQ4Njg=",
                "avatar_url": "https://avatars0.githubusercontent.com/u/5804868?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/qingyunha",
                "html_url": "https://github.com/qingyunha",
                "followers_url": "https://api.github.com/users/qingyunha/followers",
                "following_url": "https://api.github.com/users/qingyunha/following{/other_user}",
                "gists_url": "https://api.github.com/users/qingyunha/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/qingyunha/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/qingyunha/subscriptions",
                "organizations_url": "https://api.github.com/users/qingyunha/orgs",
                "repos_url": "https://api.github.com/users/qingyunha/repos",
                "events_url": "https://api.github.com/users/qingyunha/events{/privacy}",
                "received_events_url": "https://api.github.com/users/qingyunha/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T09:57:58Z",
            "updated_at": "2016-08-28T09:57:58Z",
            "author_association": "NONE",
            "body": "is this reasonable that  Template-Not-Found is an OS error?\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/242966343",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-242966343",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 242966343,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0Mjk2NjM0Mw==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-08-28T10:00:06Z",
            "updated_at": "2016-08-28T10:00:06Z",
            "author_association": "MEMBER",
            "body": "I don't really know but changing it won't solve the problem (because there might be other errors that get accidentally caught)\n\nOn 28 August 2016 11:58:09 CEST, qingyunha notifications@github.com wrote:\n\n> is this reasonable that  Template-Not-Found is an OS error?\n> \n> ## \n> \n> You are receiving this because you commented.\n> Reply to this email directly or view it on GitHub:\n> https://github.com/pallets/flask/issues/1995#issuecomment-242966274\n\n## \n\nSent from my Android device with K-9 Mail. Please excuse my brevity.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/244933204",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-244933204",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 244933204,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0NDkzMzIwNA==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-06T12:21:25Z",
            "updated_at": "2016-09-06T12:21:25Z",
            "author_association": "MEMBER",
            "body": "We could also detect if the exception is of the exact type `socket.error`, and not a subclass.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/247030468",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-247030468",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 247030468,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0NzAzMDQ2OA==",
            "user": {
                "login": "Luavis",
                "id": 1534596,
                "node_id": "MDQ6VXNlcjE1MzQ1OTY=",
                "avatar_url": "https://avatars3.githubusercontent.com/u/1534596?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Luavis",
                "html_url": "https://github.com/Luavis",
                "followers_url": "https://api.github.com/users/Luavis/followers",
                "following_url": "https://api.github.com/users/Luavis/following{/other_user}",
                "gists_url": "https://api.github.com/users/Luavis/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Luavis/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Luavis/subscriptions",
                "organizations_url": "https://api.github.com/users/Luavis/orgs",
                "repos_url": "https://api.github.com/users/Luavis/repos",
                "events_url": "https://api.github.com/users/Luavis/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Luavis/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-14T14:26:22Z",
            "updated_at": "2016-09-14T14:26:22Z",
            "author_association": "NONE",
            "body": "We can probably determine error is not subclass of `OSError` but `socket.error`. `socket.error` inherit not only `OSError` but also `IOError` ([FYI](https://www.python.org/dev/peps/pep-3151/#socket)).\n\n``` python\nissubclass(socket.error, IOError)  # True\nissubclass(socket.error, OSError)  # True\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/247031753",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-247031753",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 247031753,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0NzAzMTc1Mw==",
            "user": {
                "login": "untitaker",
                "id": 837573,
                "node_id": "MDQ6VXNlcjgzNzU3Mw==",
                "avatar_url": "https://avatars0.githubusercontent.com/u/837573?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/untitaker",
                "html_url": "https://github.com/untitaker",
                "followers_url": "https://api.github.com/users/untitaker/followers",
                "following_url": "https://api.github.com/users/untitaker/following{/other_user}",
                "gists_url": "https://api.github.com/users/untitaker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/untitaker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/untitaker/subscriptions",
                "organizations_url": "https://api.github.com/users/untitaker/orgs",
                "repos_url": "https://api.github.com/users/untitaker/repos",
                "events_url": "https://api.github.com/users/untitaker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/untitaker/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-14T14:30:14Z",
            "updated_at": "2016-09-14T14:30:14Z",
            "author_association": "MEMBER",
            "body": "Yes, but also:\n\n``` python\nissubclass(OSError, IOError)  # True\nissubclass(IOError, OSError)  # True\n```\n\nSo I don't think this will help us much.\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/247034306",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-247034306",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 247034306,
            "node_id": "MDEyOklzc3VlQ29tbWVudDI0NzAzNDMwNg==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2016-09-14T14:37:58Z",
            "updated_at": "2016-09-14T14:43:06Z",
            "author_association": "MEMBER",
            "body": "``` python\n>>> # Python 3\n>>> socket.error is OSError\nTrue\n>>> socket.error()\nOSError()\n```\n\nIn Python 3, `socket.error` isn't a subclass, it's just an alias of `OSError`.  In Python 2 it is a distinct type, _and_ not a subclass of `OSError`.\n\n``` python\n>>> # Python 2\n>>> issubclass(socket.error, OSError)\nFalse\n```\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/304721802",
            "html_url": "https://github.com/pallets/flask/issues/1995#issuecomment-304721802",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/1995",
            "id": 304721802,
            "node_id": "MDEyOklzc3VlQ29tbWVudDMwNDcyMTgwMg==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2017-05-29T19:50:13Z",
            "updated_at": "2017-05-29T19:50:13Z",
            "author_association": "MEMBER",
            "body": "This is an issue with Werkzeug's dev server, not with Flask. Other servers such as Gunicorn do not have the issue. Reported at pallets/werkzeug#1127."
        }
    ]
}