{
    "url": "https://api.github.com/repos/pallets/flask/issues/3385",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/3385/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/3385/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/3385/events",
    "html_url": "https://github.com/pallets/flask/issues/3385",
    "id": 505703898,
    "node_id": "MDU6SXNzdWU1MDU3MDM4OTg=",
    "number": 3385,
    "title": "flask db init error",
    "user": {
        "login": "danerlt",
        "id": 14197717,
        "node_id": "MDQ6VXNlcjE0MTk3NzE3",
        "avatar_url": "https://avatars2.githubusercontent.com/u/14197717?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/danerlt",
        "html_url": "https://github.com/danerlt",
        "followers_url": "https://api.github.com/users/danerlt/followers",
        "following_url": "https://api.github.com/users/danerlt/following{/other_user}",
        "gists_url": "https://api.github.com/users/danerlt/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/danerlt/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/danerlt/subscriptions",
        "organizations_url": "https://api.github.com/users/danerlt/orgs",
        "repos_url": "https://api.github.com/users/danerlt/repos",
        "events_url": "https://api.github.com/users/danerlt/events{/privacy}",
        "received_events_url": "https://api.github.com/users/danerlt/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 4,
    "created_at": "2019-10-11T08:10:20Z",
    "updated_at": "2019-10-11T14:51:53Z",
    "closed_at": "2019-10-11T14:51:53Z",
    "author_association": "NONE",
    "body": "### Expected Behavior\r\nI use `flask db init` execute error\r\n\r\n```python\r\nfrom flask import Flask\r\nfrom flask_sqlalchemy import SQLAlchemy\r\nfrom flask_migrate import Migrate\r\n\r\napp = Flask(__name__)\r\napp.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///app.db'\r\n\r\ndb = SQLAlchemy(app)\r\nmigrate = Migrate(app, db)\r\n\r\n\r\nclass User(db.Model):\r\n    id = db.Column(db.Integer, primary_key=True)\r\n    name = db.Column(db.String(128))\r\n\r\n\r\n@app.route('/')\r\ndef hello_world():\r\n    return 'Hello World!'\r\n\r\n\r\nif __name__ == '__main__':\r\n    app.run()\r\n\r\n```\r\n\r\n### Actual Behavior\r\n<!-- Tell us what happens instead. -->\r\n\r\n```pytb\r\n$ flask db init\r\nTraceback (most recent call last):\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"D:\\data\\conda\\envs\\sys_server\\Scripts\\flask.exe\\__main__.py\", line 9, in <module>\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\site-packages\\flask\\cli.py\", line 966, in main\r\n    cli.main(prog_name=\"python -m flask\" if as_module else None)\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\site-packages\\flask\\cli.py\", line 586, in main\r\n    return super(FlaskGroup, self).main(*args, **kwargs)\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\site-packages\\click\\core.py\", line 1132, in invoke\r\n    cmd_name, cmd, args = self.resolve_command(ctx, args)\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\site-packages\\click\\core.py\", line 1171, in resolve_command\r\n    cmd = self.get_command(ctx, cmd_name)\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\site-packages\\flask\\cli.py\", line 527, in get_command\r\n    self._load_plugin_commands()\r\n  File \"d:\\data\\conda\\envs\\sys_server\\lib\\site-packages\\flask\\cli.py\", line 523, in _load_plugin_commands\r\n    self.add_command(ep.load(), ep.name)\r\n  File \"C:\\Users\\tao\\AppData\\Roaming\\Python\\Python37\\site-packages\\pkg_resources\\__init__.py\", line 2345, in load\r\n    self.require(*args, **kwargs)\r\n  File \"C:\\Users\\tao\\AppData\\Roaming\\Python\\Python37\\site-packages\\pkg_resources\\__init__.py\", line 2368, in require\r\n    items = working_set.resolve(reqs, env, installer, extras=self.extras)\r\n  File \"C:\\Users\\tao\\AppData\\Roaming\\Python\\Python37\\site-packages\\pkg_resources\\__init__.py\", line 789, in resolve\r\n    raise VersionConflict(dist, req).with_context(dependent_req)\r\npkg_resources.ContextualVersionConflict: (Jinja2 2.10 (c:\\users\\tao\\appdata\\roaming\\python\\python37\\site-packages), Requirement.parse('Jinja2>=2.10.1'),\r\n {'Flask'})\r\n\r\n```\r\n\r\n### Environment\r\n\r\n* Python version: Python 3.7.3\r\n* Flask version: 1.0.2\r\n* Werkzeug version:0.16.0\r\n* Flask-Migrate version: 2.5.2\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/540965121",
            "html_url": "https://github.com/pallets/flask/issues/3385#issuecomment-540965121",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3385",
            "id": 540965121,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU0MDk2NTEyMQ==",
            "user": {
                "login": "danerlt",
                "id": 14197717,
                "node_id": "MDQ6VXNlcjE0MTk3NzE3",
                "avatar_url": "https://avatars2.githubusercontent.com/u/14197717?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/danerlt",
                "html_url": "https://github.com/danerlt",
                "followers_url": "https://api.github.com/users/danerlt/followers",
                "following_url": "https://api.github.com/users/danerlt/following{/other_user}",
                "gists_url": "https://api.github.com/users/danerlt/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/danerlt/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/danerlt/subscriptions",
                "organizations_url": "https://api.github.com/users/danerlt/orgs",
                "repos_url": "https://api.github.com/users/danerlt/repos",
                "events_url": "https://api.github.com/users/danerlt/events{/privacy}",
                "received_events_url": "https://api.github.com/users/danerlt/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-10-11T08:17:58Z",
            "updated_at": "2019-10-11T08:17:58Z",
            "author_association": "NONE",
            "body": "I use `flask run`, 'flask --help' will also appear,but I use `flask --version` is right,it print\r\n```\r\nPython 3.7.3\r\nFlask 1.1.1\r\nWerkzeug 0.16.0\r\n```"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/540965763",
            "html_url": "https://github.com/pallets/flask/issues/3385#issuecomment-540965763",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3385",
            "id": 540965763,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU0MDk2NTc2Mw==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-10-11T08:19:53Z",
            "updated_at": "2019-10-11T08:19:53Z",
            "author_association": "MEMBER",
            "body": "looks like a problem on your side to me. try upgrading jinja2..."
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/540971577",
            "html_url": "https://github.com/pallets/flask/issues/3385#issuecomment-540971577",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3385",
            "id": 540971577,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU0MDk3MTU3Nw==",
            "user": {
                "login": "danerlt",
                "id": 14197717,
                "node_id": "MDQ6VXNlcjE0MTk3NzE3",
                "avatar_url": "https://avatars2.githubusercontent.com/u/14197717?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/danerlt",
                "html_url": "https://github.com/danerlt",
                "followers_url": "https://api.github.com/users/danerlt/followers",
                "following_url": "https://api.github.com/users/danerlt/following{/other_user}",
                "gists_url": "https://api.github.com/users/danerlt/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/danerlt/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/danerlt/subscriptions",
                "organizations_url": "https://api.github.com/users/danerlt/orgs",
                "repos_url": "https://api.github.com/users/danerlt/repos",
                "events_url": "https://api.github.com/users/danerlt/events{/privacy}",
                "received_events_url": "https://api.github.com/users/danerlt/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-10-11T08:35:04Z",
            "updated_at": "2019-10-11T08:36:34Z",
            "author_association": "NONE",
            "body": "@ThiefMaster I use `pip install --upgrade jinja2` command to upgrade jinja2,  still did not solve my problem.\r\n```\r\n$ pip install --upgrade Jinja2\r\nLooking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple\r\nCollecting Jinja2\r\n  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-a\r\nny.whl (125kB)\r\n     |\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588| 133kB 168kB/s\r\nCollecting MarkupSafe>=0.23 (from Jinja2)\r\n  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/65/c6/2399700d236d1dd681af8aebff1725558cddfd6e43d7a5184a675f4711f5/MarkupSafe-1.1.1-cp37-cp37m-\r\nwin_amd64.whl\r\nInstalling collected packages: MarkupSafe, Jinja2\r\nSuccessfully installed Jinja2-2.10.3 MarkupSafe-1.1.1\r\n\r\n```\r\n"
        },
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/541096992",
            "html_url": "https://github.com/pallets/flask/issues/3385#issuecomment-541096992",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3385",
            "id": 541096992,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU0MTA5Njk5Mg==",
            "user": {
                "login": "davidism",
                "id": 1242887,
                "node_id": "MDQ6VXNlcjEyNDI4ODc=",
                "avatar_url": "https://avatars1.githubusercontent.com/u/1242887?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/davidism",
                "html_url": "https://github.com/davidism",
                "followers_url": "https://api.github.com/users/davidism/followers",
                "following_url": "https://api.github.com/users/davidism/following{/other_user}",
                "gists_url": "https://api.github.com/users/davidism/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/davidism/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/davidism/subscriptions",
                "organizations_url": "https://api.github.com/users/davidism/orgs",
                "repos_url": "https://api.github.com/users/davidism/repos",
                "events_url": "https://api.github.com/users/davidism/events{/privacy}",
                "received_events_url": "https://api.github.com/users/davidism/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-10-11T14:51:26Z",
            "updated_at": "2019-10-11T14:51:52Z",
            "author_association": "MEMBER",
            "body": "I can't reproduce this issue. It sounds like a problem with your Python installation. The original error definitely means you need to upgrade to at least Jinja 2.10.1, but beyond that I can't say why it's failing. Try staring fresh with a new virtualenv."
        }
    ]
}