{
    "url": "https://api.github.com/repos/pallets/flask/issues/3389",
    "repository_url": "https://api.github.com/repos/pallets/flask",
    "labels_url": "https://api.github.com/repos/pallets/flask/issues/3389/labels{/name}",
    "comments_url": "https://api.github.com/repos/pallets/flask/issues/3389/comments",
    "events_url": "https://api.github.com/repos/pallets/flask/issues/3389/events",
    "html_url": "https://github.com/pallets/flask/issues/3389",
    "id": 506209557,
    "node_id": "MDU6SXNzdWU1MDYyMDk1NTc=",
    "number": 3389,
    "title": "Cannot raise HTTPException()",
    "user": {
        "login": "sonnguyen2201",
        "id": 53045534,
        "node_id": "MDQ6VXNlcjUzMDQ1NTM0",
        "avatar_url": "https://avatars0.githubusercontent.com/u/53045534?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sonnguyen2201",
        "html_url": "https://github.com/sonnguyen2201",
        "followers_url": "https://api.github.com/users/sonnguyen2201/followers",
        "following_url": "https://api.github.com/users/sonnguyen2201/following{/other_user}",
        "gists_url": "https://api.github.com/users/sonnguyen2201/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sonnguyen2201/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sonnguyen2201/subscriptions",
        "organizations_url": "https://api.github.com/users/sonnguyen2201/orgs",
        "repos_url": "https://api.github.com/users/sonnguyen2201/repos",
        "events_url": "https://api.github.com/users/sonnguyen2201/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sonnguyen2201/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2019-10-12T16:41:52Z",
    "updated_at": "2019-10-12T16:48:31Z",
    "closed_at": "2019-10-12T16:48:31Z",
    "author_association": "NONE",
    "body": "```python\r\nfrom flask_api import FlaskAPI\r\nfrom flask import request\r\nfrom werkzeug.exceptions import HTTPException\r\nfrom flask import json\r\n\r\n\r\napp = FlaskAPI(__name__)\r\n\r\n\r\n@app.errorhandler(HTTPException)\r\ndef handle_exception(e):\r\n    \"\"\"Return JSON instead of HTML for HTTP errors.\"\"\"\r\n    # start with the correct headers and status code from the error\r\n    response = e.get_response()\r\n    # replace the body with JSON\r\n    response.data = json.dumps({\r\n        \"code\": e.code,\r\n        \"name\": e.name,\r\n        \"description\": e.description,\r\n    })\r\n    response.content_type = \"application/json\"\r\n    return response\r\n\r\n\r\n@app.route('/', methods=['GET'])\r\ndef get_value():\r\n    key = request.args.get('key')\r\n\r\n    if not key:\r\n        raise HTTPException(\"HELLO\")\r\n\r\n    return \"done\"\r\n\r\n\r\nif __name__ == \"__main__\":\r\n    app.run(debug=True)\r\n\r\n```\r\nWhen making a request on `http://127.0.0.1:5000/` I get:\r\n```html\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\r\n<title>None Unknown Error</title>\r\n<h1>Unknown Error</h1>\r\n<p>HELLO</p>\r\n```\r\nBy changing the original code by:\r\n```python\r\n    if not key:\r\n        raise HTTPException()\r\n```\r\nI thought that the code above will assign the error as HTTP error and  I expect the result would return JSON instead of HTML but it doesn't work.\r\n\r\n- Another try on `http://127.0.0.1:5000/abcdef`, I get:\r\n```json\r\n{\r\n    \"code\": 404,\r\n    \"description\": \"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.\",\r\n    \"name\": \"Not Found\"\r\n}\r\n```\r\n\r\n\r\n### Environment\r\n\r\n* Python version: 3.7\r\n* Flask version: 1.1.1\r\n* Werkzeug version: 0.16.0\r\n",
    "comments_inline": [
        {
            "url": "https://api.github.com/repos/pallets/flask/issues/comments/541341592",
            "html_url": "https://github.com/pallets/flask/issues/3389#issuecomment-541341592",
            "issue_url": "https://api.github.com/repos/pallets/flask/issues/3389",
            "id": 541341592,
            "node_id": "MDEyOklzc3VlQ29tbWVudDU0MTM0MTU5Mg==",
            "user": {
                "login": "ThiefMaster",
                "id": 179599,
                "node_id": "MDQ6VXNlcjE3OTU5OQ==",
                "avatar_url": "https://avatars1.githubusercontent.com/u/179599?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/ThiefMaster",
                "html_url": "https://github.com/ThiefMaster",
                "followers_url": "https://api.github.com/users/ThiefMaster/followers",
                "following_url": "https://api.github.com/users/ThiefMaster/following{/other_user}",
                "gists_url": "https://api.github.com/users/ThiefMaster/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/ThiefMaster/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/ThiefMaster/subscriptions",
                "organizations_url": "https://api.github.com/users/ThiefMaster/orgs",
                "repos_url": "https://api.github.com/users/ThiefMaster/repos",
                "events_url": "https://api.github.com/users/ThiefMaster/events{/privacy}",
                "received_events_url": "https://api.github.com/users/ThiefMaster/received_events",
                "type": "User",
                "site_admin": false
            },
            "created_at": "2019-10-12T16:43:53Z",
            "updated_at": "2019-10-12T16:44:23Z",
            "author_association": "MEMBER",
            "body": "Raising a plain `HTTPException` does not really make sense. You are supposed to use the subclasses corresponding to HTTP status codes, e.g. `BadRequest` for your example.\r\n\r\nOr you can just access `request.args['key']` in this particular case - the KeyError caused by this will be a special one that triggers a Bad Request HTTP error."
        }
    ]
}